- hosts: localhost
  vars:
    repository: mvn-releases
    group: org.test
    artifact: webwolf
    version: 1.7
  tasks:
    - name: Upload component to Nexus Repository
      shell: curl -v -u "{{ item.user }}":"{{ item.password }}" \
             -X POST "http://{{ item.instance_url }}/service/rest/v1/components?repository={{ repository }}" \
             -F maven2.groupId="{{ group }}" \
             -F maven2.artifactId="{{ artifact }}" \
             -F maven2.version="{{ version }}" \
             -F maven2.asset1=@/Users/sotudeko/Development/scan-artifacts/java/webwolf-8.0.0.M21.jar \
             -F maven2.asset1.extension=jar \
             -F maven2.generate-pom=true
      with_items:
        - { instance_url: 'localhost:8081', user: admin, password: admin123 }
      register: op

    - debug:
        var: op

