- hosts: localhost
  vars:
    image_name: local-jenkins
    version: 1.67
  tasks:
    - name: Push image to local registry
      docker_image:
        name: "{{ image_name }}"
        repository: "{{ item.registry }}"
        tag: "{{ version }}"
        push: yes
        pull: no
      with_items:
        - { registry: 'sola.localhost:18082' }
      register: op

    - debug:
        var: op

