---
nexus_admin_password: 'admin123' 
current_nexus_admin_password: 'admin123' 

# Nexus default properties
nexus_default_port: 8081
nexus_default_context_path: '/'

nexus_blob_names:           # Splited blob name list @ blob_vars.yml
  pypi:
    blob: 'default'
  raw:
    blob: 'default'
  docker:
    blob: 'default'
  ruby:
    blob: 'default'
  bower:
    blob: 'default'
  npm:
    blob: 'default'
  mvn:
    blob: 'default'
  gitlfs:
    blob: 'default'

_nexus_repos_maven_defaults:
  blob_store: "{{ nexus_blob_names.mvn.blob }}"
  strict_content_validation: true
  version_policy: release # release, snapshot or mixed
  layout_policy: strict # strict or permissive
  write_policy: allow_once # allow_once or allow
  