apiVersion: v1
kind: Service
metadata:
  name: nxrm3-service
spec:
  type: NodePort
  ports:
    - targetPort: 8081
      name: nxrm3
      port: 8081
      nodePort: 30081
  selector:
    app: nxrm3
