# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8081, host: 8011

  config.vm.provision :shell, path: "config_vm.sh"
end
