apiVersion: v1
kind: Service
metadata:
  name: nxiq-service
spec:
  type: NodePort
  ports:
    - targetPort: 8070
      name: ui
      port: 8070
      nodePort: 30070
    - targetPort: 8071
      name: admin
      port: 8071
      nodePort: 30071
  selector:
    app: nxiq
